# Generated by Django 4.2.3 on 2023-12-23 21:06

import carsaleproject.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsaleapp', '0002_alter_caradd_frontimage_alter_caradd_interiorimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradd',
            name='frontimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='caradd',
            name='interiorimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='caradd',
            name='sideimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PrivateMediaStorage(), upload_to=''),
        ),
    ]
