# Generated by Django 4.2.3 on 2024-01-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsaleapp', '0002_newuser_otp_attempts_alter_newuser_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='otp',
        ),
    ]
