# Generated by Django 4.2.3 on 2023-12-25 19:48

import carsaleproject.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsaleapp', '0004_alter_caradd_frontimage_alter_caradd_interiorimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradd',
            name='frontimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PublicMediaStorage(), upload_to='front/'),
        ),
        migrations.AlterField(
            model_name='caradd',
            name='interiorimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PublicMediaStorage(), upload_to='interior/'),
        ),
        migrations.AlterField(
            model_name='caradd',
            name='sideimage',
            field=models.ImageField(storage=carsaleproject.storage_backends.PublicMediaStorage(), upload_to='side/'),
        ),
    ]
