# Generated by Django 4.2.3 on 2024-01-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carsaleapp', '0005_newuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='one_time_otp_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
