# Generated by Django 4.2.3 on 2024-01-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsaleapp', '0006_newuser_one_time_otp_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='one_time_otp_attempts',
        ),
    ]
